---
  - name: Distribution name/version
    vars:
      distro_name: "{{ ansible_distribution }}"
      distro_version: "{{ ansible_distribution_version}}" 
    debug: msg="{{ distro_name , distro_version }}"
...
